// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqbxusluiykvzxlbwdns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxYnh1c2x1aXlrdnp4bGJ3ZG5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0ODYzMTUsImV4cCI6MjA2NDA2MjMxNX0.Y1It8lrzdLH5UP9CVDjaOgyPP12Qg5sFypuzh570oS8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);